# docker-compose.yml
version: "3"

services:
  db:                             # service "db" for  MySQL database.
    build:
      context: ./db-mysql         # build Docker image from Dockerfile
    ports:
      - "3306:3306"               # For allowing external access to MySQL db, Map host machine's port 3306 to container's port 3306.
    networks:
      - wordpress-net             # Connects service to "wordpress-net" network.
    volumes:
      - db_data:/var/lib/mysql    # Creating volume (db_data) to persistently store MySQL data.
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: my_db
      MYSQL_USER: farasat
      MYSQL_PASSWORD: 123         # Sets environment variables for MySQL service

  wordpress:
    build:
      context: ./wordpress
    ports:
      - "8080:80"                 # For allowing external access to WordPress application, Map host machine's port 8080 to container's port 80
    networks:
      - wordpress-net
    depends_on:
      - db
    environment:                  # variables used by the WordPress Docker image to configure the connection to the MySQL service
      WORDPRESS_DB_HOST: db       # hostname of the MySQL server= service name of the MySQL container
      WORDPRESS_DB_USER: farasat  # MySQL user that WordPress should use to connect to the database
      WORDPRESS_DB_PASSWORD: 123  # password for the MySQL user that WordPress should use.
      WORDPRESS_DB_NAME: my_db    # name of the MySQL database that WordPress should use
    volumes:
      - wp_data:/var/www/html

networks:
  wordpress-net:
    driver: bridge                # Defines a custom bridge network named "wordpress-net."

volumes:                          # Defined 2 volumes (db_data and wp_data) for persistent storage of MySQL and WordPress data.
  db_data:
  wp_data:
